config/routes.rb
Sharemyride::Application.routes.draw do
  root :to => 'home#index'

  get '/trips/search' => 'trips#search'
  post '/trips/:id/book' => 'trips#book', :as => :book
  resources :trips

  devise_for :users

end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id            :integer          not null, primary key
#  trip_position :integer
#  name          :string(255)
#  lat           :string(255)
#  long          :string(255)
#  trip_id       :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Location < ActiveRecord::Base
  # mass data assignment allowed for these attributes
  attr_accessible :trip_position, :name, :lat, :long, :trip_id

  # table associations
  belongs_to :trip

  # db validations applied to attributes

end

app/models/passenger.rb
# == Schema Information
#
# Table name: passengers
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  trip_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Passenger < ActiveRecord::Base
  # mass data assignment allowed for these attributes
  attr_accessible :user_id, :trip_id

  # table associations
  belongs_to :trip
  belongs_to :user

  #validation
  validates :user_id, uniqueness: { scope: :trip_id}
end

app/models/traveller.rb
# == Schema Information
#
# Table name: travellers
#
#  id         :integer          not null, primary key
#  role       :string(255)
#  name       :string(255)
#  num_seats  :integer
#  user_id    :integer
#  trip_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Traveller < ActiveRecord::Base
  # mass data assignment allowed for these attributes
  attr_accessible :role, :name, :num_seats, :user_id, :trip_id

  # table associations
  belongs_to :trip
  belongs_to :user

end

app/models/trip.rb
# == Schema Information
#
# Table name: trips
#
#  id              :integer          not null, primary key
#  dept_date       :datetime
#  total_seats     :integer
#  seats_available :integer
#  seat_cost       :decimal(8, 2)
#  driver_id       :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Trip < ActiveRecord::Base
  before_create :setup_available_seats
  # mass data assignment allowed for these attributes
  attr_accessible :dept_date, :total_seats, :seats_available, :seat_cost, :driver_id, :locations_attributes

  # table associations
  has_many :passengers, dependent: :destroy
  has_many :locations, dependent: :destroy
  belongs_to :driver, :foreign_key => 'driver_id', :class_name => 'User'
  accepts_nested_attributes_for :locations

  # db validations applied to attributes
  validates :dept_date, :total_seats, :seat_cost, :presence => true
  validates :total_seats, numericality: { only_integer: true }
  validates :seat_cost, numericality: true
  validate :dept_date_cannot_be_in_the_past

  def dept_date_cannot_be_in_the_past
    if dept_date.present? && dept_date < Date.today
      errors.add(:dept_date, "can't be in the past")
    end
  end

  def setup_available_seats
    self.seats_available = self.total_seats
  end

  def start_point
    locations.where(:trip_position => 0).first
  end

  def end_point
    locations.where(:trip_position => 1).first
  end

  def search_query
    #move the code to build up the seach query here
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :passengers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/trips_controller.rb
  class TripsController < ApplicationController
  before_filter :load_driver_trips, :only => [:new, :create]

  def load_driver_trips
    @driver_trips = Trip.where(driver_id: current_user.id).where('dept_date > ?', Time.now.beginning_of_day).order(:dept_date)
  end

  def show
    # find a selected trip
    @trip = Trip.find(params[:id])

    respond_to do |format|
      format.json { render :json => @trip, :include => :locations }
      format.html
    end
  end

  def index
    # instead of finding all trips only find those >= today
    @trips = Trip.where('dept_date > ?', Time.now.beginning_of_day).where.not(user_id: current_user.id).order(:dept_date)
  end

  def search
    # if the date search parameter is supplied
    if params[:date].present?
      # get all the trips on or after the supplied date
      @trips = Trip.where('dept_date >= ?', params[:date])
    else
      # get all the trips after today
      @trips = Trip.where('dept_date > ?', Time.now.beginning_of_day).order(:dept_date)
    end

    # if the departure location is supplied
    if params[:depart].present?
      # get all the trips with the supplied departure location
      depart = params[:depart]
      @trips = @trips.select do |trip|
        depart.in?(
          trip.locations.where(:trip_position => 0).map(&:name)
        )
      end
    end

    # if the destination location is supplied
    if params[:destination].present?
      # get all the trips with the supplied destination location
      destination = params[:destination]
      @trips = @trips.select do |trip|
        destination.in?(
          trip.locations.where(:trip_position => 1).map(&:name)
        )
      end
    end
    #raise params.inspect

    render :index
  end

  def new
    # find seats a driver has booked
    @booked_seats = Passenger.where(:user_id => current_user.id).map(&:trip)

    # initialize a new trip
    @trip = Trip.new
    @locationA = Location.new
    @locationA.trip_position = 0
    @locationB = Location.new
    @locationB.trip_position = 1
    @trip.locations << @locationA
    @trip.locations << @locationB
  end

  def create
    @trip = Trip.new(params[:trip])
    @trip.driver_id = current_user.id

    if @trip.save
      redirect_to new_trip_path
    else
      @booked_seats = Passenger.where(:user_id => current_user.id).map(&:trip)
      #logger.debug @trip.errors.to_json
      render :action => :new
    end
  end

  def edit
    # find a selected trip
    @trip = Trip.find(params[:id])
  end

  def update
    # commit changes to an existing trip
    @trip = Trip.find(params[:id])

    if @trip.update_attributes(params[:trip])
      redirect_to new_trip_path
    else
      render :action => :edit
    end
  end

  def destroy
    # remove a selected trip
    @trip = Trip.find(params[:id])

    if @trip.destroy
      redirect_to new_trip_path
    else
      render :action => :edit
    end
  end

  def book
    @trip = Trip.find(params[:id])
    if @trip.seats_available > 0
      @passenger = Passenger.new

      @passenger.trip_id = @trip.id
      @passenger.user_id = current_user.id
      @passenger.save

      @trip.seats_available -= 1
      @trip.save
    end

    respond_to do |format|
      format.json { render :json => @trip }
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    # used by the layout file to dynamically update the page title
    content_for(:title) { page_title }
  end

  def avatar_url(user)
    #create the gravitar
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)

    #link the gravitar to the user on the trip
    "http://gravatar.com/avatar/#{gravatar_id}.png?d=mm"
  end
end

app/views/home/index.html.erb
<!-- Application Helper method title will reference this tag and render it's value in layout view-->
<% title 'Search' %>

<div id="search-container" class="row">

  <div class="large-12 columns search">

    <div class="row">
      <div class="large-12 columns">
        <h1>Catch a lift to anywhere.</h1>
      </div>
    </div>

    <div class="row search-bar">

      <%= form_tag '/trips/search', class: 'custom geocode', :method => 'get' do %>
      <!-- Use the geocode.js to auto complete the departure and destination city fields -->
        <div class="large-4 columns">
          <%= text_field_tag 'depart',nil, placeholder: 'Departure City', class:'depart'  %>
        </div>

        <div class="large-4 columns">
          <%= text_field_tag 'destination',nil, placeholder: 'Destination City', class: 'destination' %>
        </div>

        <div class="large-2 columns">
          <%= text_field_tag 'date', nil, placeholder: Date.today, class: 'date'%>
        </div>

        <div class="large-2 columns">
          <input type="submit" id="search-button" value="Search" />
        </div>

      <%end %>

    </div>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
<meta charset="utf-8" />

<!-- Uncomment to make IE8 render like IE7 -->
<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

<!-- Set the viewport width to device width for mobile -->
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link href='http://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>

<!-- Application Helper method title will return the title value for each page -->
<title>ShareMyRide <%= yield :title %></title>

<%= stylesheet_link_tag "application" %>
<%= javascript_include_tag "vendor/custom.modernizr" %>
<%= csrf_meta_tags %>
</head>

<body>
<!-- Header and Nav -->
<section id="main">

<div class="row header">
  <div class="large-3 columns">
    <h1>Sharemyride</h1>
  </div>
  <div class="large-9 columns">
    <ul class="button-group right">
      <li><a class="button" href="/">Home</a></li>
      <%= render 'devise/menu/registration_items' %>
      <%= render 'devise/menu/login_items' %>
    </ul>
  </div>
</div>

<!-- End Header and Nav -->


<!-- First Band (Image) -->

<div class="row body">
  <div class="large-12 columns">
    <%= yield %>
  </div>
</div>
<div class="push">
</div>
</section>

<!-- Footer -->

<footer class="row footer">
  <div class="large-12 columns">
    <hr />
    <div class="row">
      <div class="large-6 columns">
        <p>&copy; Copyright Sharemyride.</p>
      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">
          <li><a href="/">Home</a></li>
          <% if user_signed_in? %>
            <li><%= link_to('My Trips', new_trip_path) %></li>
            <li><%= link_to('Edit registration', edit_user_registration_path) %></li>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
        <% else %>
            <li><%= link_to('Login', new_user_session_path)  %></li>
            <li><%= link_to('Register', new_user_registration_path)  %></li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
</footer>
<script src="https://maps.googleapis.com/maps/api/js?sensor=false&libraries=places" type="text/javascript"></script>
<%= javascript_include_tag "application" %>
</body>
</html>

app/views/trips/_errors.html.erb
<% if @trip.errors.any? %>
<ol>
  <% @trip.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ol>
<% end %>

app/views/trips/_trip.html.erb
<div class="row">
  <div class="large-1 columns"><%= image_tag( avatar_url(trip.driver) ) %></div>

  <!-- only allow user to view trip details if they're signed in -->
  <div class="large-2 columns">
    <% if user_signed_in? %>
      <%= link_to trip.dept_date.strftime("%a, %m-%d-%y"), trip_path(trip.id) %>
    <% else %>
      <%= trip.dept_date.strftime("%a, %m-%d-%y") %>
    <% end %>
  </div>

  <!-- show the google map and render the route of the selected trip  map.js -->
  <div class="large-3 columns"><%= link_to trip.start_point.name,  trip_path(trip), :class => "map-modal" %></div>
  <div class="large-3 columns"><%= trip.end_point.name %></div>

  <!-- booking.js updates the seats available when the book button is clicked -->
  <div class="large-1 columns" id="seats-<%=trip.id%>"><%= trip.seats_available %></div>
  <div class="large-1 columns"><%= number_to_currency(trip.seat_cost) %></div>

  <!-- only allow user to book a seat on a trip if they're signed in -->
  <div class="large-1 columns">
    <!-- The  -->
    <% if user_signed_in? && ! (trip.id.in?(current_user.passengers.map &:trip_id)) %>
      <%= link_to "Book", book_path(trip), :class => "btn_book button" %>
    <% end %>
  </div>
</div>

app/views/trips/_triptable.html.erb
<!-- Foundation reveal modal logic that will display the map for the trip route -->
<div id="myModal" class="reveal-modal">
  <div id="map-canvas" style="width:400px;height:300px; max-width:400px; max-height:300px;"></div>
</div>
<%= render :partial => "trips/trip", :collection => @trips %>

app/views/trips/edit.html.erb
<!-- Application Helper method title will reference this tag and render it's value in layout view-->
<% title 'Alter' %>

<div class="row page-body">
  <%= render :partial => "errors" %>

  <h1>Alter Trip Information</h1>

  <div class="large-6 columns">
    <%= form_for(@trip, html: {class:'custom geocode'}) do |f| %>
      <%= label_tag(:dept_date, "Departure Date") %>
      <%= f.text_field(:dept_date, class: 'date') %>

      <%= label_tag(:total_seats, "Available Seats") %>
      <%= f.text_field(:total_seats) %>

      <%= label_tag(:seat_cost, "Price") %>
      <%= f.text_field(:seat_cost) %>

      <% @trip.locations.each do |location| %>
        <%= f.fields_for :locations, location do |location_fields| %>
          <%= label_tag(:name, location.trip_position == 0 ? 'Depart': 'Destination') %>
          <%= location_fields.text_field(:name, class:location.trip_position == 0 ? 'depart': 'destination' ) %>
          <%= location_fields.hidden_field :trip_position %>
        <% end %>
      <% end %>

      <%= f.submit "Save Trip", :class => 'button' %>
      <%= link_to('Cancel Trip', @trip, method: :delete, :class => "button") %>
    <% end %>
  </div>

</div>

app/views/trips/index.html.erb
 <div class="row page-body">

  <h1>All Trips</h1>

  <div class="large-12 columns">
    <%= render :partial => "triptable" %>
  </div>

</div>

app/views/trips/new.html.erb
<!-- Application Helper method title will reference this tag and render it's value in layout view-->
<% title 'Add' %>

<div class="row page-body">

  <div class="large-5 columns">
    <h2>Add Trip</h2>
    <%= render :partial => "errors" %>
    <%= form_for(@trip, html: {class:'custom geocode'}) do |f| %>

      <%= label_tag(:dept_date, "Departure Date") %>
      <%= f.text_field(:dept_date, class: 'date') %>

      <%= label_tag(:total_seats, "Total Seats") %>
      <%= f.text_field(:total_seats) %>

      <%= label_tag(:seat_cost, "Price") %>
      <%= f.text_field(:seat_cost) %>

      <% @trip.locations.each do |location| %>
        <%= f.fields_for :locations, location do |location_fields| %>
          <%= label_tag(:name, location.trip_position == 0 ? 'Depart': 'Destination') %>
          <%= location_fields.text_field(:name, class:location.trip_position == 0 ? 'depart': 'destination' ) %>
          <!-- hidden fields stil generate html tags that can be referenced to access data -->
          <%= location_fields.hidden_field :trip_position %>
          <%= location_fields.hidden_field :lat %>
          <%= location_fields.hidden_field :long %>
        <% end %>
      <% end %>

      <%= f.submit "Save Trip", :class => 'button' %>
    <% end %>
  </div>

   <div class="large-7 columns">
      <h2>Trips you have scheduled</h2>
      <!-- display trip details for the user-->
      <table>
        <thead>
          <tr>
            <td>Depart Date</td>
            <td>Departure</td>
            <td>Destination</td>
            <td>Total Seats</td>
            <td>Booked Seats</td>
            <td>Price</td>
          </tr>
        </thead>
      </div>

      <!-- loop through all the trips associated with the user and list them here -->
       <% @driver_trips.each do |trip| %>
        <tr>
          <td><%= link_to(trip.dept_date.strftime("%a, %m-%d-%y"), edit_trip_path(trip.id)) %></td>
          <td><%= trip.start_point.name %></td>
          <td><%= trip.end_point.name %></td>
          <td><%= trip.total_seats %></td>
          <td><%= trip.seats_available %></td>
          <td><%= number_to_currency(trip.seat_cost) %></td>
        </tr>
       <% end %>
   </table>

    <h2>Seats you have booked</h2>
    <table>
      <thead>
        <tr>
          <td>Depart Date</td>
          <td>Departure</td>
          <td>Destination</td>
          <td>Price</td>
        </tr>
      </thead>
      <% @booked_seats.each do |seat| %>
        <tr>
          <td><%= link_to seat.dept_date.strftime("%a, %m-%d-%y"), trip_path(seat.id) %></td>
          <td><%= seat.start_point.name %></td>
          <td><%= seat.end_point.name %></td>
          <td><%= number_to_currency(seat.seat_cost) %></td>
        </tr>
      <% end %>
    </table>

</div>

app/views/trips/show.html.erb
<!-- Application Helper method title will reference this tag and render it's value in layout view-->
<% title 'This Trip' %>

 <div class="row page-body">
  <div class="large-6 columns">

    <div class="row">
      <div class="large-12 columns">
        <%= render :partial => "errors" %>
         <h1>Trip Information</h1>
      </div>
    </div>

    <!-- Driver Profile -->
    <div class="row">
      <div class="large-6 columns"><%= image_tag( avatar_url(@trip.driver) ) %></div>
      <div class="large-6 columns"><%= @trip.driver.email %></div>
    </div>

    <!-- Trip Details -->
    <div class="row">
      <div class="large-6 columns">Departure Date</div>
      <div class="large-6 columns"><%= @trip.dept_date.strftime("%a, %m-%d-%y") %></div>
    </div>

    <div class="row">
      <div class="large-6 columns">Departure Point</div>
      <div class="large-6 columns"><%= @trip.start_point.name %></div>
    </div>

    <div class="row">
      <div class="large-6 columns">Destination</div>
      <div class="large-6 columns"><%= @trip.end_point.name %></div>
    </div>

    <div class="row">
      <div class="large-6 columns">Available Seats</div>
      <!-- booking.js updates the seats available-->
      <div class="large-6 columns" id="seats-<%= @trip.id %>"><%= @trip.seats_available %></div>
    </div>

    <div class="row">
      <div class="large-6 columns">Seat Price</div>
      <div class="large-6 columns"><%= number_to_currency(@trip.seat_cost)  %></div>
    </div>

    <div class="row">
      <div class="large-6 columns"><%= link_to('Book Seat', book_path(@trip), :class => "btn_book button") %></div>
      <div class="large-6 columns"><%= link_to('Route Map', @trip, :class => "btn_map button") %></div>
    </div>
  </div>
        <!-- Show the route on a map -->
    <div class="large-6 columns">
      <div id="map-canvas" style="width:450px; height:450px;"></div>
    </div>

</div>